Add update-chrome function

diff --git a/bash/bashrc b/bash/bashrc
--- a/bash/bashrc
+++ b/bash/bashrc
@@ -81,5 +81,19 @@ update-discord () {
     fi       
 }
 
+update-chrome () {
+    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
+        wget "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb" -O /tmp/chrome_latest_amd64.deb
+        if [[ $? -ne 0 ]]; then
+            echo "Network error!" >&2
+            return 1
+        fi
+        sudo dpkg -i /tmp/chrome_latest_amd64.deb
+        return 0
+    else
+        echo "Not linux" >&2
+        return 1
+    fi
+}    
 
 source "$OSH"/oh-my-bash.sh
