Add update-discord, update update-vscode

diff --git a/bash/bashrc b/bash/bashrc
--- a/bash/bashrc
+++ b/bash/bashrc
@@ -51,13 +51,35 @@ export EDITOR="$(which emacs) -nw"
 export GIT_EDITOR=$EDITOR
 
 # utility functions
-update_vscode () {
+update-vscode () {
     if [[ "$OSTYPE" == "linux-gnu"* ]]; then
         wget 'https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64' -O /tmp/code_latest_amd64.deb
+        if [[ $? -ne 0 ]]; then
+           echo "Network error!" >&2
+           return 1
+        fi
         sudo dpkg -i /tmp/code_latest_amd64.deb
+        return 0
     else
-        echo "Not linux"
+        echo "Not linux" >&2
+        return 1
     fi
 }
+
+update-discord () {
+    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
+        wget 'https://discord.com/api/download/stable?platform=linux&format=deb' -O /tmp/discord_latest_amd64.deb
+        if [[ $? -ne 0 ]]; then
+           echo "Network error!" >&2
+           return 1
+        fi
+        sudo dpkg -i /tmp/discord_latest_amd64.deb
+        return 0
+    else
+        echo "Not linux" >&2
+        return 1
+    fi       
+}
+
 
 source "$OSH"/oh-my-bash.sh
